### ISSUE TITLE
Mesh DLNR not working with splat trained in 0.3.1

### ISSUE THREAD

**Issue by bbartlett-nv** [openvdb/fvdb-reality-capture#179]
(fvdb) $ frgs mesh-dlnr frgs_logs/run_2025-12-05-15-31-48/checkpoints/00210000/reconstruct_ckpt.pt 0.1
2025-12-05 20:11:48,149 - fvdb_reality_capture.cli.frgs._mesh_dlnr - INFO - Loading Gaussian splats from from frgs_logs/run_2025-12-05-15-31-48/checkpoints/00210000/reconstruct_ckpt.pt
Traceback (most recent call last):
  File "/home/bbartlett/miniconda3/envs/fvdb/bin/frgs", line 7, in <module>
    sys.exit(frgs())
             ^^^^^^
  File "/media/bbartlett/datadrive/Code/fvdb/dev/new_repo/fvdb-reality-capture/fvdb_reality_capture/cli/frgs/__init__.py", line 25, in frgs
    cmd.execute()
  File "/media/bbartlett/datadrive/Code/fvdb/dev/new_repo/fvdb-reality-capture/fvdb_reality_capture/cli/frgs/_mesh_dlnr.py", line 120, in execute
    NormalizeScene(normalization_type=self.normalization_type),
                                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MeshDLNR' object has no attribute 'normalization_type'
(fvdb) $ pip list | grep fvdb
fvdb-core                     0.3.1
fvdb_reality_capture          0.3.1       /media/bbartlett/datadrive/Code/fvdb/dev/new_repo/fvdb-reality-capture
